apiVersion: v1
kind: Template
metadata:
  name: coolstore-pipeline-template
objects:
- apiVersion: "v1" 
  kind: "BuildConfig"
  metadata:
    name: "sample-pipeline12"
  spec:
    source:
      git:
        uri: "https://github.com/sourabhgupta385/coolstore-microservice-ui.git"
    strategy:
      jenkinsPipelineStrategy:
        env:
        -  name: foo
           value: ${foo}
