kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/sourabhgupta385/coolstore-microservice-ui.git"
  strategy:
    jenkinsPipelineStrategy:
      env:
       - name: "FOO"
         value: "BAR"
